/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.pr1.gui;

import com.sun.glass.ui.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.pr1.bean.Objects;
import org.pr1.structures.DoublyLinkedList;
/**
 *
 * @author Sorge
 */
public class EDObjectsDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditObjectsDialog
     */
    private Objects object = new Objects();
    private String strObjectImage = "";
    private DoublyLinkedList dblObjects = new DoublyLinkedList();
    private static EDObjectsDialog instance;
    public static EDObjectsDialog getInstance(Frame parent, boolean modal){
        if(instance == null){
            instance = new EDObjectsDialog(parent, modal);
        }
        return instance;
    }
    
    public EDObjectsDialog(java.awt.Frame parent, boolean modal, DoublyLinkedList dblObjects) {
        super(parent, modal);
        initComponents();      
        this.setLocationRelativeTo(parent);
        this.dblObjects = dblObjects;
        tableObjects.setModel(new ObjectsTableModel(this.dblObjects));
    }
    
    public EDObjectsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();      
        this.setLocationRelativeTo(parent);
    }
    
    public DoublyLinkedList getListObjects(){
        return this.dblObjects;
    }
    
    private Font getCustomFont(float size){
        Font font = null;
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, new File("temp/atari.ttf")).deriveFont(size);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(font);
        } catch (IOException|FontFormatException e) {
            //font = new Font("Segoe UI Semibold", 0, Integer.parseInt((String.valueOf(size))));
        }
        return font;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlContainer = new javax.swing.JPanel();
        txtObjectName = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableObjects = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        pnlObjectImage = new javax.swing.JPanel();
        lblObjectImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar/Eliminar objetos");

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));

        txtObjectName.setFont(getCustomFont(8));
        txtObjectName.setForeground(new java.awt.Color(153, 153, 153));
        txtObjectName.setFocusable(false);

        btnOK.setFont(getCustomFont(7));
        btnOK.setText("Aceptar");
        btnOK.setEnabled(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        tableObjects.setFont(getCustomFont(7));
        tableObjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableObjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableObjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableObjectsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableObjects);

        lblTitle.setBackground(new java.awt.Color(0, 153, 204));
        lblTitle.setFont(getCustomFont(22));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Editar/Eliminar objetos");
        lblTitle.setOpaque(true);

        btnCancel.setFont(getCustomFont(7));
        btnCancel.setText("Cancelar");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setFont(getCustomFont(7));
        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setFont(getCustomFont(7));
        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        pnlObjectImage.setBackground(new java.awt.Color(255, 255, 255));
        pnlObjectImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlObjectImage.setPreferredSize(new java.awt.Dimension(75, 75));
        pnlObjectImage.setLayout(new java.awt.GridBagLayout());

        lblObjectImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObjectImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/pr1/resources/no_image.png"))); // NOI18N
        lblObjectImage.setToolTipText("Click para agregar imagen");
        lblObjectImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblObjectImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblObjectImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblObjectImageMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -2;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 14, 12, 11);
        pnlObjectImage.add(lblObjectImage, gridBagConstraints);

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                                .addComponent(pnlObjectImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addComponent(txtObjectName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addComponent(pnlObjectImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblObjectImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObjectImageMouseClicked
        if(!btnEdit.isEnabled()){
            JFileChooser fcSearch = new JFileChooser("../Documents/");
            FileFilter ffFilter = new FileNameExtensionFilter("Archivos de imagen (*.jpg, *.jpeg, *.png, *.gif)", "jpg", "jpeg", "png", "gif");
            fcSearch.setFileFilter(ffFilter);
            try{
                if(JFileChooser.APPROVE_OPTION == fcSearch.showDialog(this, "Aceptar")){
                    ImageIcon img = new ImageIcon(ImageIO.read(fcSearch.getSelectedFile()));
                    strObjectImage = fcSearch.getSelectedFile().getAbsolutePath();
                    Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblObjectImage.getWidth(), lblObjectImage.getHeight(), Image.SCALE_DEFAULT));
                    lblObjectImage.setIcon(icon);
                }
            }catch(IOException ex){
                Logger.getLogger(AddObjectsFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblObjectImageMouseClicked

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if(!txtObjectName.getText().isEmpty()){
            if(!strObjectImage.isEmpty()){
                Path path = Paths.get(strObjectImage);
                object.setName(txtObjectName.getText());
                object.setImage(path.getFileName().toString());
                File newFile = new File("temp/".concat(path.getFileName().toString()));
                try {
                    copyImage(strObjectImage, newFile.getAbsolutePath());
                } catch (IOException ex) {
                    Logger.getLogger(AddObjectsFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                lblObjectImage.setIcon(new ImageIcon(getClass().getResource("/org/pr1/resources/no_image.png")));
                strObjectImage = "";
                enabledToEdit(0);
                this.dblObjects.set(tableObjects.getSelectedRow(), this.object);  
                tableObjects.revalidate();
                tableObjects.repaint();
                tableObjects.clearSelection();
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    public void copyImage(String source, String dest) throws FileNotFoundException, IOException {
        Path FROM = Paths.get(source);
        Path TO = Paths.get(dest);
        CopyOption[] options = new CopyOption[]{
          StandardCopyOption.REPLACE_EXISTING,
          StandardCopyOption.COPY_ATTRIBUTES
        }; 
        Files.copy(FROM, TO, options);
    }
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        enabledToEdit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        enabledToEdit(1);
    }//GEN-LAST:event_btnEditActionPerformed

    private void enabledToEdit(int option){
        switch(option){
            case 0:
                txtObjectName.setFocusable(false);
                btnCancel.setEnabled(false);
                btnOK.setEnabled(false);
                btnEdit.setEnabled(true);
                btnDelete.setEnabled(true);
                lblObjectImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                break;
            case 1:
                txtObjectName.setFocusable(true);
                btnCancel.setEnabled(true);
                btnOK.setEnabled(true);
                btnEdit.setEnabled(false);
                btnDelete.setEnabled(false);
                lblObjectImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                break;
        }
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(tableObjects.getSelectedRows().length > 0){
            Objects object = this.dblObjects.get(tableObjects.getSelectedRow());
            this.dblObjects.remove(object);
            if(this.dblObjects.size() > 0){
                tableObjects.revalidate();
                tableObjects.repaint();
            }else{
                JOptionPane.showMessageDialog(null, "No existen objetos.");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableObjectsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableObjectsMousePressed
        if(tableObjects.getSelectedRows().length > 0){
            this.object = this.dblObjects.get(tableObjects.getSelectedRow());
            ImageIcon img = new ImageIcon("temp/".concat(this.object.getImage()));
            Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblObjectImage.getWidth(), lblObjectImage.getHeight(), Image.SCALE_DEFAULT));
            lblObjectImage.setIcon(icon);
            txtObjectName.setText(this.object.getName());
            lblObjectImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            File newFile = new File("temp/".concat(this.object.getImage()));
            strObjectImage = newFile.getAbsolutePath();
        }
    }//GEN-LAST:event_tableObjectsMousePressed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDObjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDObjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDObjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDObjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EDObjectsDialog dialog = new EDObjectsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblObjectImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlObjectImage;
    private javax.swing.JTable tableObjects;
    private javax.swing.JTextField txtObjectName;
    // End of variables declaration//GEN-END:variables
}
