/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.pr1.gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;
import org.pr1.bean.Objects;
import org.pr1.structures.DoublyLinkedList;
import org.pr1.structures.OrthogonalMatrix;

/**
 *
 * @author Sorge
 */
public class StageDialog extends javax.swing.JDialog {

    /**
     * Creates new form ScreenDialog
     */
    private DoublyLinkedList dblObjects = new DoublyLinkedList();
    private int option = 0;
    private int size = 0;
    private int rows = 2;
    private int cols = 4;
    private OrthogonalMatrix omStage = new OrthogonalMatrix();
    public StageDialog(java.awt.Frame parent, boolean modal, DoublyLinkedList dblObjects) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.dblObjects = dblObjects;
        this.size = this.dblObjects.size() - 1;
        for (int row = 0; row < rows; row++) {
            omStage.addRow(cols);
        }
        pnlStage.setLayout(new GridBagLayout());
        createRowsAndCols(rows, cols);
        ImageIcon img = new ImageIcon("temp/".concat(dblObjects.getLast().getImage()));
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblObjectImage.getWidth(), lblObjectImage.getHeight(), Image.SCALE_DEFAULT));
        lblObjectImage.setIcon(icon);
        btnPrev.setEnabled(false);
        if(this.dblObjects.size() == 1){
            btnNext.setEnabled(false);
        }
    }

    public StageDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private Font getCustomFont(float size){
        Font font = null;
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, new File("temp/atari.ttf")).deriveFont(size);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(font);
        } catch (IOException|FontFormatException e) {
            //font = new Font("Segoe UI Semibold", 0, Integer.parseInt((String.valueOf(size))));
        }
        return font;
    }
    
    private void createRowsAndCols(int rows, int cols){
        pnlStage.removeAll();
        GridBagConstraints gbc = new GridBagConstraints(); 
        for (int row = 0; row < rows; row++) {
            for (int col = 0; col < cols; col++) {
                gbc.anchor = GridBagConstraints.FIRST_LINE_START;
                gbc.gridx = col;
                gbc.gridy = row;
                CellPane cellPane = new CellPane();
                Border border = null;
                if (row < (rows - 1)) {
                    if (col < (cols - 1)) {
                        border = new MatteBorder(1, 1, 0, 0, Color.GRAY);
                    } else {
                        border = new MatteBorder(1, 1, 0, 1, Color.GRAY);
                    }
                } else {
                    if (col < (cols - 1)) {
                        border = new MatteBorder(1, 1, 1, 0, Color.GRAY);
                    } else {
                        border = new MatteBorder(1, 1, 1, 1, Color.GRAY);
                    }
                }
                cellPane.setBorder(border);
                if(row == (rows - 1) && col == (cols - 1)){
                    gbc.weightx = 0.5;
                    gbc.weighty = 0.5;
                }
                pnlStage.add(cellPane, gbc);
            }
        }
        pnlStage.revalidate();
        pnlStage.repaint();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlVisor = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblObjectImage = new javax.swing.JLabel();
        btnAddRow = new javax.swing.JButton();
        lblRow = new javax.swing.JLabel();
        lblCol = new javax.swing.JLabel();
        btnAddCol = new javax.swing.JButton();
        scrollStage = new javax.swing.JScrollPane();
        pnlStage = new javax.swing.JPanel();
        lblOption = new javax.swing.JLabel();
        cbxOption = new javax.swing.JComboBox();
        btnDeleteRow = new javax.swing.JButton();
        btnDeleteCol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear escenario");

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));

        pnlVisor.setBackground(new java.awt.Color(255, 255, 255));
        pnlVisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPrev.setText("<");
        btnPrev.setSelected(true);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.setSelected(true);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblObjectImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObjectImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/pr1/resources/no_image.png"))); // NOI18N
        lblObjectImage.setToolTipText("");
        lblObjectImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblObjectImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblObjectImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblObjectImageMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlVisorLayout = new javax.swing.GroupLayout(pnlVisor);
        pnlVisor.setLayout(pnlVisorLayout);
        pnlVisorLayout.setHorizontalGroup(
            pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlVisorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblObjectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlVisorLayout.setVerticalGroup(
            pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlVisorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblObjectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        btnAddRow.setFont(getCustomFont(7));
        btnAddRow.setText("Agregar");
        btnAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRowActionPerformed(evt);
            }
        });

        lblRow.setFont(getCustomFont(10));
        lblRow.setText("Fila:");

        lblCol.setFont(getCustomFont(10));
        lblCol.setText("Columna:");

        btnAddCol.setFont(getCustomFont(7));
        btnAddCol.setText("Agregar");
        btnAddCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddColActionPerformed(evt);
            }
        });

        pnlStage.setBackground(new java.awt.Color(204, 204, 204));
        pnlStage.setLayout(new java.awt.GridBagLayout());
        scrollStage.setViewportView(pnlStage);

        lblOption.setFont(getCustomFont(10));
        lblOption.setText("Seleccion:");

        cbxOption.setFont(getCustomFont(9));
        cbxOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pila", "Cola" }));
        cbxOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOptionActionPerformed(evt);
            }
        });

        btnDeleteRow.setFont(getCustomFont(7));
        btnDeleteRow.setText("Borrar");
        btnDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRowActionPerformed(evt);
            }
        });

        btnDeleteCol.setFont(getCustomFont(7));
        btnDeleteCol.setText("Borrar");
        btnDeleteCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteColActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollStage)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addComponent(pnlVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOption)
                            .addComponent(lblCol)
                            .addComponent(lblRow))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddRow, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(btnAddCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDeleteRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteCol, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 507, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addComponent(btnDeleteRow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteCol))
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOption))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddRow)
                                    .addComponent(lblRow))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddCol)
                                    .addComponent(lblCol))))
                        .addGap(18, 18, 18)))
                .addComponent(scrollStage, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddColActionPerformed
        cols++;
        createRowsAndCols(rows, cols);
        //this.omStage.addColumn(rows);
    }//GEN-LAST:event_btnAddColActionPerformed

    private void btnAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRowActionPerformed
        rows++;
        createRowsAndCols(rows, cols);
        //this.omStage.addRow(cols);
    }//GEN-LAST:event_btnAddRowActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(cbxOption.getSelectedIndex() == 0){
            size--;
            if(size >= 0 && size < this.dblObjects.size()){
                Objects object = this.dblObjects.get(size);
                ImageIcon img = new ImageIcon("temp/".concat(object.getImage()));
                Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblObjectImage.getWidth(), lblObjectImage.getHeight(), Image.SCALE_DEFAULT));
                lblObjectImage.setIcon(icon);
                if(size == 0){
                    btnNext.setEnabled(false);
                    btnPrev.setEnabled(true);
                }
            }
        }else{
            size++;
            if(size >= 0 && size < this.dblObjects.size()){
                Objects object = this.dblObjects.get(size);
                ImageIcon img = new ImageIcon("temp/".concat(object.getImage()));
                Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblObjectImage.getWidth(), lblObjectImage.getHeight(), Image.SCALE_DEFAULT));
                lblObjectImage.setIcon(icon);
                if(size == (this.dblObjects.size()-1)){
                    btnNext.setEnabled(false);
                    btnPrev.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if(cbxOption.getSelectedIndex() == 0){
            size++;
            if(size >= 0 && size < this.dblObjects.size()){
                btnNext.setEnabled(true);
                Objects object = this.dblObjects.get(size);
                ImageIcon img = new ImageIcon("temp/".concat(object.getImage()));
                Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblObjectImage.getWidth(), lblObjectImage.getHeight(), Image.SCALE_DEFAULT));
                lblObjectImage.setIcon(icon);
                if(size == (this.dblObjects.size()-1)){
                    btnNext.setEnabled(true);
                    btnPrev.setEnabled(false);
                }
            }
        }else if(cbxOption.getSelectedIndex() == 1){
            size--;
            if(size >= 0 && size < this.dblObjects.size()){
                btnNext.setEnabled(true);
                Objects object = this.dblObjects.get(size);
                ImageIcon img = new ImageIcon("temp/".concat(object.getImage()));
                Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblObjectImage.getWidth(), lblObjectImage.getHeight(), Image.SCALE_DEFAULT));
                lblObjectImage.setIcon(icon);
                if(size == 0){
                    btnNext.setEnabled(true);
                    btnPrev.setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void cbxOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOptionActionPerformed
        ImageIcon img = null;
        if(cbxOption.getSelectedIndex() == 0){
            this.size = this.dblObjects.size() - 1;
            img = new ImageIcon("temp/".concat(dblObjects.getLast().getImage()));
        }else if(cbxOption.getSelectedIndex() == 1){
            this.size = 0;
            img = new ImageIcon("temp/".concat(dblObjects.getFirst().getImage()));
        }
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(lblObjectImage.getWidth(), lblObjectImage.getHeight(), Image.SCALE_DEFAULT));
        lblObjectImage.setIcon(icon);
        if(this.dblObjects.size() > 1){
            btnNext.setEnabled(true);
        }else{
            btnNext.setEnabled(true);
        }
        btnPrev.setEnabled(false);
    }//GEN-LAST:event_cbxOptionActionPerformed

    private void lblObjectImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObjectImageMousePressed
        Icon icon = lblObjectImage.getIcon();
        BufferedImage bi = new BufferedImage(icon.getIconWidth(),icon.getIconHeight(),BufferedImage.TYPE_INT_RGB);
        Const.setImage(new ImageIcon(bi));
    }//GEN-LAST:event_lblObjectImageMousePressed

    private void btnDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRowActionPerformed
        rows--;
        createRowsAndCols(rows, cols);
    }//GEN-LAST:event_btnDeleteRowActionPerformed

    private void btnDeleteColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteColActionPerformed
        cols--;
        createRowsAndCols(rows, cols);
    }//GEN-LAST:event_btnDeleteColActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StageDialog dialog = new StageDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCol;
    private javax.swing.JButton btnAddRow;
    private javax.swing.JButton btnDeleteCol;
    private javax.swing.JButton btnDeleteRow;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JComboBox cbxOption;
    private javax.swing.JLabel lblCol;
    private javax.swing.JLabel lblObjectImage;
    private javax.swing.JLabel lblOption;
    private javax.swing.JLabel lblRow;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlStage;
    private javax.swing.JPanel pnlVisor;
    private javax.swing.JScrollPane scrollStage;
    // End of variables declaration//GEN-END:variables
}
